java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@393a77e3[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7c38f600[Wrapped task = Thread[Thread-10661927,5,main]]] rejected from java.util.concurrent.ThreadPoolExecutor@4be346a9[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 10661924]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at cs451.links.FairLossLinks.send(FairLossLinks.java:56)
	at cs451.links.StubbornLinks.lambda$sendAckMessagesToBeSent$3(StubbornLinks.java:126)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at cs451.links.StubbornLinks.sendAckMessagesToBeSent(StubbornLinks.java:121)
	at cs451.links.StubbornLinks.lambda$new$0(StubbornLinks.java:59)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
	at cs451.udp.UDPReceiver.run(UDPReceiver.java:50)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523)
	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
	... 2 more
